services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - ./api/src:/app/src
